# -*- coding: utf-8 -*-
"""crop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ewoc5yJx1GWEy_7bMzgmwrp3-s-cfrq_
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
import pickle

df = pd.read_csv("kn.csv")
df.head()

df= df.drop(['State','District','Crop'],axis=1)

from sklearn.preprocessing import LabelEncoder
l3= LabelEncoder()
df['Season']=l3.fit_transform(df['Season'])

data = df.drop("Season",axis='columns')

data["Season"]= df['Season']


Yield = df["Production"]/df["Area"]
df["Yield"]= Yield 

X = df[['District_Id', 'Temprature','Rainfall','Crop_Id','Area']]
y = df['Yield']

from sklearn import linear_model
regr = linear_model.LinearRegression()
regr.fit(X, y)

pred_yield = regr.predict([[30,28,111,10,5]])

print(pred_yield)

pickle.dump(regr, open('model.pkl','wb'))

#Loading model to compare the results
model = pickle.load(open('model.pkl','rb'))
print(model.predict([[0,27,114,0,24574]]))



